In [ ]:
# Student Grades Prediction with Machine Learning
# https://thecleverprogrammer.com/2021/04/16/student-grades-prediction-with-machine-learning/
#Öğrenci final not tahmini(lineer regresyon ile)

In [ ]:
#Gerekli kütüphaneleri import edelim.

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

In [26]:
# CSV dosyasını URL üzerinden yükleme
url = "https://raw.githubusercontent.com/amankharwal/Website-data/master/student-mat.csv"
data = pd.read_csv(url)

# Veri setinin ilk 5 satırını görüntüleme
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

 Bu veri setinde G1, ilk dönemin notlarını, G2, ikinci dönemin notlarını ve G3, final notlarını temsil eder. 
 Şimdi verileri hazırlayalım ve öğrencilerin final notlarını nasıl tahmin edebileceğimizi görelim.

In [27]:
import numpy as np
import pandas as pd

#final notu tahmini
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"

x = np.array(data.drop([predict], axis=1))  # 'G3' sütununu düşürmek için axis=1
y = np.array(data[predict])

# Eğitim ve test verilerine ayırma
from sklearn.model_selection import train_test_split

#veri setini %20 test ve %80 eğitim olarak böldük.
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [28]:
linear_regression = LinearRegression()
linear_regression.fit(X_train, y_train)
accuracy = linear_regression.score(X_test, y_test)
print(accuracy)

0.8163420571454503


In [ ]:
# %87'lik doğru tahmin.Şimdi tahminlere bakalım.

predictions = linear_regression.predict(X_test)
for i in range(len(predictions)):
    print(predictions[x], X_test[x], [y_test[x]])

[[10.29696269  6.03908993 11.91770645  4.4733173   6.03908993]
 [10.29696269 10.29696269 11.91770645  4.4733173  12.62222157]
 [ 3.44928216 15.3935389  11.91770645 16.50994112  8.41111514]
 ...
 [ 8.41111514 15.3935389  18.46730903 16.50994112 16.50994112]
 [ 6.04679334 14.24958397 18.46730903  4.4733173   4.4733173 ]
 [15.3935389  11.23199219 18.46730903  4.4733173  10.29696269]] [[[10 11  4  0 10]
  [ 7  7  3  0  6]
  [11 12  2  0 10]
  [ 6  5  1  0  7]
  [ 7  7  3  0  6]]

 [[10 11  4  0 10]
  [10 11  4  0 10]
  [11 12  2  0 10]
  [ 6  5  1  0  7]
  [13 13  3  0  0]]

 [[ 6  5  1  2  0]
  [16 15  3  0  9]
  [11 12  2  0 10]
  [16 16  1  0  0]
  [10  9  3  0  4]]

 ...

 [[10  9  3  0  4]
  [16 15  3  0  9]
  [19 18  3  0  0]
  [16 16  1  0  0]
  [16 16  1  0  0]]

 [[ 6  7  2  1 15]
  [15 14  2  0  2]
  [19 18  3  0  0]
  [ 6  5  1  0  7]
  [ 6  5  1  0  7]]

 [[16 15  3  0  9]
  [10  9  2  0 75]
  [19 18  3  0  0]
  [ 6  5  1  0  7]
  [10 11  4  0 10]]] [array([[11,  7, 13,  6,  7]